let pending;
function open(){return pending||(pending=new Promise((resolve,reject)=>{const r=indexedDB.open('moony-studio',1);r.onupgradeneeded=()=>{r.result.createObjectStore('entries',{keyPath:'id'});r.result.createObjectStore('state',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>{pending=null;reject(r.error)};r.onblocked=()=>{pending=null;reject(new Error('Close other studio tabs and try again.'))}}))}
async function transact(table,mode,fn){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(table,mode);const req=fn(tx.objectStore(table));tx.oncomplete=()=>resolve(req.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Storage transaction cancelled.'))})}
export const all=()=>transact('entries','readonly',s=>s.getAll());
export const put=e=>transact('entries','readwrite',s=>s.put(e));
export const remove=id=>transact('entries','readwrite',s=>s.delete(id));
export const state=async()=>await transact('state','readonly',s=>s.get('progress'))||{id:'progress',completed:[],positions:{},checked:{}};
export const saveState=s=>transact('state','readwrite',t=>t.put(s));
export async function importEntries(entries,progress){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(['entries','state'],'readwrite');for(const e of entries)tx.objectStore('entries').put(e);if(progress)tx.objectStore('state').put(progress);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Import cancelled.'))})}
export async function migrateLegacy(){let pics;try{pics=JSON.parse(localStorage.getItem('rk_pics')||'[]')}catch{return}if(!Array.isArray(pics))return;const log=await transact('state','readonly',s=>s.get('legacy-import'))||{id:'legacy-import',ids:[]};const existing=new Set(log.ids);for(const p of pics){if(typeof p.src!=='string'||!/^data:image\/(png|jpeg|webp);base64,/.test(p.src))continue;let hash=2166136261;for(let i=0;i<p.src.length;i++)hash=Math.imul(hash^p.src.charCodeAt(i),16777619);const id=`rakan-${p.t}-${hash>>>0}`;if(!existing.has(id)){await put({id,src:p.src,date:new Date(Number(p.t)||Date.now()).toISOString(),lesson:'Rakan drawing',note:'Copied from My pictures. Original retained.',origin:'rakan'});log.ids.push(id);await transact('state','readwrite',s=>s.put(log));}}}
export async function preparePhoto(file){if(!file.type.startsWith('image/'))throw new Error('Choose a photo image.');if(file.size>25*1024*1024)throw new Error('Choose an image smaller than 25 MB.');const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await new Promise((res,rej)=>{image.onload=res;image.onerror=()=>rej(new Error('This image format cannot be read. Try a JPEG or PNG.'))});const scale=Math.min(1,1400/Math.max(image.width,image.height));const c=document.createElement('canvas');c.width=Math.round(image.width*scale);c.height=Math.round(image.height*scale);const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,c.width,c.height);x.drawImage(image,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.86)}finally{URL.revokeObjectURL(url)}}
